# Form implementation generated from reading ui file 'frnDesencriptar.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # ====================================================================
        # BOTÓN CARGAR ARCHIVO
        # ====================================================================
        self.btnCargarArchivo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCargarArchivo.setGeometry(QtCore.QRect(30, 30, 740, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCargarArchivo.setFont(font)
        self.btnCargarArchivo.setObjectName("btnCargarArchivo")
        
        # ====================================================================
        # LABEL
        # ====================================================================
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 110, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        # ====================================================================
        # TEXT EDIT - MENSAJE ENCRIPTADO
        # ====================================================================
        self.txtMensajeEncriptado = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtMensajeEncriptado.setGeometry(QtCore.QRect(30, 150, 550, 350))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtMensajeEncriptado.setFont(font)
        self.txtMensajeEncriptado.setReadOnly(True)
        self.txtMensajeEncriptado.setObjectName("txtMensajeEncriptado")
        
        # ====================================================================
        # BOTONES
        # ====================================================================
        self.btnDesencriptar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDesencriptar.setGeometry(QtCore.QRect(620, 150, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDesencriptar.setFont(font)
        self.btnDesencriptar.setObjectName("btnDesencriptar")
        
        self.btnDescargar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDescargar.setGeometry(QtCore.QRect(620, 220, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDescargar.setFont(font)
        self.btnDescargar.setObjectName("btnDescargar")
        
        self.btnRegresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegresar.setGeometry(QtCore.QRect(620, 450, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setObjectName("btnRegresar")
        
        # ====================================================================
        # ESTABLECER WIDGET CENTRAL
        # ====================================================================
        MainWindow.setCentralWidget(self.centralwidget)
        
        # ====================================================================
        # STATUSBAR (Opcional - lo puedes dejar o quitar)
        # ====================================================================
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ====================================================================
        # TRADUCCIÓN Y CONEXIÓN
        # ====================================================================
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Desencriptar Mensaje"))
        self.btnCargarArchivo.setText(_translate("MainWindow", "📁 Cargar Archivo Encriptado"))
        self.label.setText(_translate("MainWindow", "Mensaje Encriptado:"))
        self.txtMensajeEncriptado.setPlaceholderText(_translate("MainWindow", "Aquí se mostrará el mensaje encriptado..."))
        self.btnDesencriptar.setText(_translate("MainWindow", "🔓 Desencriptar"))
        self.btnDescargar.setText(_translate("MainWindow", "💾 Descargar"))
        self.btnRegresar.setText(_translate("MainWindow", "⬅️ Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())