# Form implementation generated from reading ui file 'frnEncriptar.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # ====================================================================
        # LABEL
        # ====================================================================
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        # ====================================================================
        # TEXT EDIT - MENSAJE
        # ====================================================================
        self.txtMensaje = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtMensaje.setGeometry(QtCore.QRect(30, 70, 550, 400))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtMensaje.setFont(font)
        self.txtMensaje.setObjectName("txtMensaje")
        
        # ====================================================================
        # BOTONES
        # ====================================================================
        self.btnEncriptar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEncriptar.setGeometry(QtCore.QRect(620, 70, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnEncriptar.setFont(font)
        self.btnEncriptar.setObjectName("btnEncriptar")
        
        self.btnDescargar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDescargar.setGeometry(QtCore.QRect(620, 140, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnDescargar.setFont(font)
        self.btnDescargar.setObjectName("btnDescargar")
        
        self.btnEnviar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEnviar.setGeometry(QtCore.QRect(620, 210, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnEnviar.setFont(font)
        self.btnEnviar.setObjectName("btnEnviar")
        
        self.btnRegresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegresar.setGeometry(QtCore.QRect(620, 420, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRegresar.setFont(font)
        self.btnRegresar.setObjectName("btnRegresar")
        
        # ====================================================================
        # ESTABLECER WIDGET CENTRAL
        # ====================================================================
        MainWindow.setCentralWidget(self.centralwidget)
        
        # ====================================================================
        # STATUSBAR (Opcional - lo puedes dejar o quitar)
        # ====================================================================
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ====================================================================
        # TRADUCCIÓN Y CONEXIÓN
        # ====================================================================
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encriptar Mensaje"))
        self.label.setText(_translate("MainWindow", "Mensaje a Encriptar:"))
        self.txtMensaje.setPlaceholderText(_translate("MainWindow", "Escribe aquí el mensaje que deseas encriptar..."))
        self.btnEncriptar.setText(_translate("MainWindow", "🔒 Encriptar"))
        self.btnDescargar.setText(_translate("MainWindow", "💾 Descargar"))
        self.btnEnviar.setText(_translate("MainWindow", "📧 Enviar"))
        self.btnRegresar.setText(_translate("MainWindow", "⬅️ Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())