# Form implementation generated from reading ui file 'frnMenu.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuEncriptar = QtWidgets.QMenu(parent=self.menubar)
        self.menuEncriptar.setObjectName("menuEncriptar")
        self.menuDesencriptar = QtWidgets.QMenu(parent=self.menubar)
        self.menuDesencriptar.setObjectName("menuDesencriptar")
        self.menuAyuda = QtWidgets.QMenu(parent=self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menusalir = QtWidgets.QMenu(parent=self.menubar)
        self.menusalir.setObjectName("menusalir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Crear_Documento = QtGui.QAction(parent=MainWindow)
        self.Crear_Documento.setObjectName("Crear_Documento")
        self.ctionCargarDocumento = QtGui.QAction(parent=MainWindow)
        self.ctionCargarDocumento.setObjectName("ctionCargarDocumento")
        self.menuEncriptar.addAction(self.Crear_Documento)
        self.menuDesencriptar.addAction(self.ctionCargarDocumento)
        self.menubar.addAction(self.menuEncriptar.menuAction())
        self.menubar.addAction(self.menuDesencriptar.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menubar.addAction(self.menusalir.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuEncriptar.setTitle(_translate("MainWindow", "Encriptar"))
        self.menuDesencriptar.setTitle(_translate("MainWindow", "Desencriptar"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.menusalir.setTitle(_translate("MainWindow", "Salir"))
        self.Crear_Documento.setText(_translate("MainWindow", "Crear Documento"))
        self.ctionCargarDocumento.setText(_translate("MainWindow", "Cargar Documento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = menu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
