# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 335)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lvluser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lvluser.setGeometry(QtCore.QRect(220, 130, 231, 41))
        self.lvluser.setObjectName("lvluser")
        self.lvlcancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lvlcancel.setGeometry(QtCore.QRect(90, 220, 111, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagen1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lvlcancel.setIcon(icon)
        self.lvlcancel.setObjectName("lvlcancel")
        self.lvlpassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lvlpassword.setGeometry(QtCore.QRect(220, 60, 231, 41))
        self.lvlpassword.setObjectName("lvlpassword")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 140, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lvlacept = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lvlacept.setGeometry(QtCore.QRect(260, 220, 111, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Imagen2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lvlacept.setIcon(icon1)
        self.lvlacept.setIconSize(QtCore.QSize(18, 18))
        self.lvlacept.setObjectName("lvlacept")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 121, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Imagen3.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lvlcancel.setText(_translate("MainWindow", "Cancelar"))
        self.label_4.setText(_translate("MainWindow", "Contraseña"))
        self.lvlacept.setText(_translate("MainWindow", "Aceptar"))
        self.label_5.setText(_translate("MainWindow", "Usuario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
